 
export const demoData = [
    {
        id: 101,
        request_details: {
            type: "Car finance",
            payout_account: 'GTB ending in 1234',
            repayment_account: 'VISA Debit ending in 1234',
            date: "Sun Nov 06 2022 16:59:49",
            asset_id: "car",
            asset_make: "BMW",
            asset_model: "M3",
        },
        status: "In Progress",
        meta_status: 2,
        product_details: {
            principal: 10000,
            interest: 2000,
            term: 1,
            term_unit: "month",
            total_cost: 12000,
            interest_percent: 20,
            repayment_amount: 20,
            repayment_frequency: 'week',
        },
        personal_details: {
            employment: 'self employed',
            income: 20000,
            address: "100 Green Street Accra Ghana",
            full_name: "John Doe",
            date_of_birth: "23/01/1997",
            phone_number: "2338022145678",
        },
    },
    {
        id: 2280,
        request_details: {
            type: "Business loan",
            payout_account: 'GTB ending in 1234',
            repayment_account: 'VISA Debit ending in 1234',
            date: "Sat Nov 05 2022 16:39:49", 
        },
        status: "In Progress",
        meta_status: 2,
        product_details: {
            principal: 10000,
            interest: 2000,
            term: 2,
            term_unit: "year",
            total_cost: 12000,
            interest_percent: 20,
            repayment_amount: 20,
            repayment_frequency: 'month',
        },
        personal_details: {
            employment: 'self employed',
            income: 20000,
            address: "100 Green Street Accra Ghana",
            full_name: "John Doe",
            date_of_birth: "23/01/1997",
            phone_number: "2338022145678",
        },
    },
    {
        id: 120,
        request_details: {
            type: "Personal loan",
            payout_account: 'GTB ending in 1234',
            repayment_account: 'VISA Debit ending in 1234',
            date: "Sun Nov 06 2022 16:59:49", 
        },
        status: "Approved",
        meta_status: 3,
        product_details: {
            principal: 10000,
            interest: 2000,
            term: 2,
            term_unit: "year",
            totalcost: 12000,
            interest_percent: 20,
            repayment_amount: 20,
            repayment_frequency: 'month',
        },
        personal_details: {
            employment: 'self employed',
            income: 20000,
            address: "100 Green Street Accra Ghana",
            full_name: "John Doe",
            date_of_birth: "23/01/1997",
            phone_number: "2338022145678",
        },
    },
    {
        id: 100,
        request_details: {
            type: "Personal loan",
            payout_account: 'GTB ending in 1234',
            repayment_account: 'VISA Debit ending in 1234',
            date: "Sun Nov 06 2022 16:59:49", 
        },
        status: "Rejected",
        meta_status: 0,
        product_details: {
            principal: 10000,
            interest: 2000,
            term: 2,
            term_unit: "year",
            total_cost: 12000,
            interest_percent: 20,
            repayment_amount: 20,
            repayment_frequency: 'month',
        },
        personal_details: {
            employment: 'self employed',
            income: 20000,
            address: "100 Green Street Accra Ghana",
            full_name: "John Doe",
            date_of_birth: "23/01/1997",
            phone_number: "2338022145678",
        },
    },
]